= Kinds

:icons: font
:syntax-highlighting:

== What are Kinds?

Kinds are the _types of types_ or better _type expressions_. We need them because not every type expression denotes a set of possible values. For example:

----
Maybe
----
 
No value actually can have type `Maybe`. Values can be of type `Maybe Int` or `Maybe [String]` and we can even speak of `Maybe a`.

But if `Maybe` is not a type, what is it then? This is exactly what kinds tell us! 
We define:

* Type expressions with kind `*` denote actual types, that is, sets of possible values.
* If k~1~ and k~2~ are kinds, then so is k~1~ -> k~2~.
A type expression with kind k~1~ -> k~2~ can be applied to another type expression of kind k~1~ and the resulting type expression has kind k~2~
* The arrow binds right associatively, so that k~1~ -> k~2~ -> k~3~ means k~1~ -> (k~2~ -> k~3~)
* If `t` is a type expression and `k` is a kind, the construct `t :: k` means "type expression `t` has (or is of) kind `k`

We can now derive the kind of type expression `Maybe`. Surely it holds that 

[code,haskell]
----
  Int :: *
  Maybe Int :: *
----

since we can imagine values like

[source,haskell]
----
5 :: Int
Just 7 :: Maybe Int
----

that inhabit those types. From this it follows that `Maybe` is something that can be applied to a type expression of kind `\*` and the resulting type expression also has kind `*`. Therefore:

[source,haskell]
----
Maybe :: * -> *
----

NOTE: Note the spaces between the double colon, the stars and the arrow! Always include them when you write kinds, because input like `::*->*` would be interpreted as an <<lexical.adoc#_operators,operator>>. 

## Kind Annotations

The compiler tries to infer the kind of each type expression occurring in the program, so normally a programmer needs not be concerned with kinds.

There may be cases where this doesn't work automatically and kind inference leads to error messages. The remedy is to write some *kind annotations*.

Kind annotations are currently allowed on variables only. Here is an example:

.Example with kind annotations
[source,haskell]
----
data Foo (f :: * -> *) a b = X (f a) (f b)

foo :: Foo Maybe Int Double
foo = X (Just 1) Nothing


bar :: Foo [] Int Double
bar = X [] [5.23, 8e-7]
----

It is recommended to annotate type variables where they are introduced:

1. in the left hand side of a `type`, `data` or `newtype` definition
2. in the list of type variables following `forall`
3. in a type class definition after the class name

NOTE: In future versions of the compiler, kind annotations will be forbidden except where stated above. 

## Annotation of Java type variable bounds

Frequently, _bounds_ are specified for type variables in Java generic types.

.Example:
[source,java]
----
class Enum<E extends Enum<E>> { ... }
----

It'll cause compiler errors when we define this in Frege as

.Wrong:
[source,haskell]
----
data Enum e = pure native java.lang.Enum{e} where { ... }
----

Instead, we need to annotate the type variable `e` with its correct bound:

.Correct:
[source,haskell]
----
data Enum (e ≤ Enum e) = pure native java.lang.Enum{e} where { ... }
----

When the Java type bound takes the form:

[source,java]
----
extends ClassType & Interface1 & Interface2 & Interface3
----
  
we write this as tuple in Frege:

[source,haskell]
----
(Classtype, Interface1, Interface2, Interface3)
----








