= Kinds

Kinds are the _types of types_ or better _type expressions_. We need them because not every type expression denotes a set of possible values. For example:

----
 Maybe
----
 
No value actually can have type `Maybe`. Values can be of type `Maybe Int` or `Maybe [String]` and we can even speak of `Maybe a`.

But if `Maybe` is not a type, what is it then? This is exactly what kinds tell us! 
We define:

* Type expressions with kind `*` denote actual types, that is, sets of possible values.
* If k~1~ and k~2~ are kinds, then so is `k`~1~ `-> k`~2~.
A type expression with kind `k`~1~ `-> k`~2~ can be applied to another type expression of kind `k`~1~ and the resulting type expression has kind `k`~2~
* The arrow binds right associatively, so that `k1 -> k2 -> k3` means `k1 -> (k2 -> k3)`
* If `t` is a type expression and `k` is a kind, the construct `t :: k` means "type expression `t` has (or is of) kind `k`

We can now derive the kind of type expression `Maybe`. Surely it holds that 

----

  Int :: *
  Maybe Int :: *

----

since we can imagine values like `5 :: Int` or `Just 7 :: Maybe Int`



